Wanderlust/Models/IVideoRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Wanderlust.Models
{
    public interface IVideoRepository
    {
        Task<IEnumerable<string>> GetVideo();
    }
}

Wanderlust/Models/MockVideoRepository.cs
using Google.Apis.Services;
using Google.Apis.YouTube.v3;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Diagnostics;

namespace Wanderlust.Models
{
    public class MockVideoRepository : IVideoRepository
    {
        private string baseUrl = "https://www.youtube.com/embed/";

        // Append to end of url so autoplay is enabled.
        // Youtube has rules/conditions where videos cannot be autoplayed with sound unless the webpage is interacted with first
        // Workaround is to autoplay video muted.
        // Future Options:
        // 1)   A video can start with sound if the user has interacted with the domain (click, tap, etc.) so have a loading page
        //      introducing webpage and then have to click on something to enter which in turn will start videos with sound
        // 2)   Start webpage as mute and then inform user to unmute with a popup
        private string setAutoplay = "?&autoplay=1";
        private string setAutoplayMuted = "?&autoplay=1&mute=1";

        public async Task<IEnumerable<string>> GetVideo()
        {
            IEnumerable<string> videos;
            
            try
            {
                Task<IEnumerable<string>> getVideoTask = Run();
                videos = await getVideoTask;
            }
            catch (AggregateException ex)
            {
                foreach (var e in ex.InnerExceptions)
                {
                    Debug.WriteLine("Error: " + e.Message);
                }

                // Add Rick Roll Video
                List<string> rickRoll = new List<string> { "https://www.youtube.com/embed/dQw4w9WgXcQ?&autoplay=1" };
                videos = rickRoll;
            }

            return videos;
        }

        private async Task<IEnumerable<string>> Run()
        {
            var youtubeService = new YouTubeService(new BaseClientService.Initializer()
            {

                ApplicationName = this.GetType().ToString()
            });

            // Add filters to search here
            var searchListRequest = youtubeService.Search.List("snippet");
            searchListRequest.Q = "Toyota Tacoma";
            searchListRequest.MaxResults = 5;
            searchListRequest.Type = "video";
            searchListRequest.VideoEmbeddable = SearchResource.ListRequest.VideoEmbeddableEnum.True__;
            searchListRequest.SafeSearch = SearchResource.ListRequest.SafeSearchEnum.Strict;

            // Add to set video location request
            //searchListRequest.Location = "";
            //searchListRequest.LocationRadius = "";

            // Call the search.list method to retrieve results matching the specified query term.
            var searchListResponse = await searchListRequest.ExecuteAsync();

            List<string> videos = new List<string>();

            // Adding results to a list as url
            foreach (var searchResult in searchListResponse.Items)
            {
                videos.Add(String.Format("{0}{1}{2}", this.baseUrl, searchResult.Id.VideoId, this.setAutoplay));
            }

            Debug.WriteLine(String.Format("Videos:\n{0}\n", string.Join("\n", videos)));

            return videos;
        }
    }
}

Wanderlust/ViewModels/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Wanderlust.ViewModels
{
    public class HomeViewModel
    {
        public string VideoUrl { get; set; }
    }
}

Wanderlust/Components/EmbeddedVideoViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Wanderlust.Models;
using Wanderlust.ViewModels;

namespace Wanderlust.Components
{
    public class EmbeddedVideoViewComponent : ViewComponent
    {
        private readonly IVideoRepository _videoRepository;
        public EmbeddedVideoViewComponent(IVideoRepository videoRepository)
        {
            _videoRepository = videoRepository;
        }

        public IViewComponentResult Invoke()
        {
            Random rnd = new Random();
            Task<IEnumerable<string>> videos = _videoRepository.GetVideo();

            string video = videos.Result.ElementAt(rnd.Next(0, videos.Result.Count()));
            HomeViewModel homeViewModel = new HomeViewModel
            {
                //VideoUrl = videos.Result.First()
                VideoUrl = videos.Result.ElementAt(rnd.Next(0, videos.Result.Count()))
            };

            return View(homeViewModel);
        }

    }
}

Wanderlust/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Wanderlust.Controllers
{
    public class HomeController : Controller
    {
        public HomeController()
        {
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Wanderlust/Views/Home/Index.cshtml
@model HomeViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Hello World!</h1>

    <h3>@ViewBag.VideoLength</h3>

    @*<iframe width="560" height="315" src="@Model.VideoUrl" allow="autoplay" allowfullscreen></iframe>*@

    <div id="embeddedVideo">
        @await Component.InvokeAsync("EmbeddedVideo")
    </div>



</div>

<script>
    @*setInterval(function () {
        $.ajax({
            url: '@Url.Action("ReloadEvents", "Home")',
            success: function (data)
            {
                $("#embeddedVideo").html(data);
            }
        })
    }, 10000); // 10 sec*@

    setInterval(function () {
        $('#embeddedVideo').load('@Url.Action("ReloadEvents", "Home")');
    }, @ViewBag.VideoLength)

</script>

Wanderlust/Views/Shared/Components/EmbeddedVideo/Default.cshtml
@model HomeViewModel

<div class="text-center">

    <iframe width="560" height="315" src="@Model.VideoUrl" allow="autoplay" allowfullscreen></iframe>

</div>

Wanderlust/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Wanderlust</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Wanderlust</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Wanderlust - <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>